######################################################################
# Automatically generated by qmake (3.0) mié mar 26 19:28:35 2014
######################################################################

TEMPLATE = app
TARGET = git
INCLUDEPATH += .

# Input
HEADERS += graficos.h
SOURCES += graficos.cpp main.cpp
QT += widgets

